export const menu = [
    {
        id: 'acc',
        label: "Dashboard",
        name: 'dashboard',
        header: "dashboard",
        icon: "ri-dashboard-3-line",
        link: '/dashboard',
        children: [],
        active: true,
        status: true,
    },
    {
        id: 'report',
        label: "Sales Report",
        name: 'sales-report',
        header: "Sales Report",
        icon: "ri-money-dollar-box-line",
        link: '/sales-report',
        children: [],
        active: true,
        status: true,
    },
    {
        id: 'inventories',
        label: `Inventory`,
        name: 'inventories',
        header: `PACKAGES`,
        icon: "ri-file-list-line",
        link: '/inventories',
        children: ['/inventories'],
        active: false,
        status: true,
        items: [
            {
                id: 'inventories',
                label: `Inventories`,
                name: 'primary_package',
                link: '/inventories',
                children: [],
                active: false,
                status: true
            },
            {
                id: 'vendors',
                label: `Vendors`,
                name: 'vendors',
                link: '/vendors',
                children: [],
                active: false,
                status: true
            },
        ]
    },
    {
        id: 'customers',
        label: "Customers",
        name: 'customers',
        icon: "ri-contacts-line",
        link: '/customers',
        children: [],
        active: true,
        status: true,
    },
];