# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build
    - name: Setup Git Client
      run: |
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        git config --global user.email "sandeshsingh265@gmail.com"
        git config --global user.name "Sandesh Singh"
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: resume.tex
        args: -xelatex -file-line-error -interaction=nonstopmode -outdir=out
    - name: Collect artifacts
      run: |
        mkdir dist
        cp out/* dist/
    - name: Push artifacts
      run: |
        git clone --depth 1 --single-branch -b deploy git@github.com:sande265/IMS.git deployment
        mv deploy/.git deploy-.git
        rm -rf deploy
        mkdir deploy
        mv deploy-.git deploy/.git
        cd deploy
        cp -R ../dist/* .
        git add .
        git diff --staged --quiet || git commit -m "Update Artifacts"
        git push
